name: "Pull Request Labeler"
on:
- pull_request_target

# Declare default permissions as read only.
permissions: read-all

jobs:
  triage:
    if: ${{ github.repository == 'Robok-Engine/Robok-Easy-UI' }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
      with:
        sync-labels: true